### ISSUE TITLE
cannot find module  ../dialog

### ISSUE THREAD

**Issue by jjgalvez** [kelyvin/Google-Allo-For-Desktop#9]
trying the linux version and I get the following error:
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/jc/Downloads/google-allo-linux(1)/Linux/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/jc/Downloads/google-allo-linux(1)/Linux/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/jc/Downloads/google-allo-linux(1)/Linux/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process.emit (/home/jc/Downloads/google-allo-linux(1)/Linux/resources/app/lib/webpack:/app/node_modules/source-map-support/source-map-support.js:439:1)

**Comment by jjgalvez** [comment]
nevermind, its because I tried to run it again without properly closing it
